on:
  push:
    branches:
      - master
name: 🚀 Deploy website master on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server:  ftp.yenum.dev
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /public_html/dashboard/

    - name: Install Packages
      run: |
        composer install —optimise-autoloader —no-dev
    - name: Deploy to Server
      uses: ngocquyhoang/deploy@laravel
      with:
          user: yenumdev
          host: yenum.dev
          port: 2083
          path: /public_html/dashboard/
          owner: owner
      env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
